/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f9f9f9',
        'on-background': '#1a1c1c',
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#4c4546',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',
        outline: '#7e7576',
        'outline-variant': '#cfc4c5',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#1b1b1b',
        'on-primary-container': '#848484',
        'inverse-primary': '#c6c6c6',
        secondary: '#af2800',
        'on-secondary': '#ffffff',
        'secondary-container': '#db3400',
        'on-secondary-container': '#fffbff',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        display: ['Space Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-caps': ['Space Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        display: ['80px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['20px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-caps': ['14px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      spacing: {
        unit: '4px',
        gutter: '32px',
        margin: '64px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      borderWidth: {
        3: '3px',
      },
      boxShadow: {
        neo: '4px 4px 0px 0px #000000',
        'neo-sm': '2px 2px 0px 0px #000000',
        'neo-lg': '8px 8px 0px 0px #000000',
        'neo-xl': '12px 12px 0px 0px #000000',
        none: '0px 0px 0px 0px #000000',
      },
      borderRadius: {
        none: '0px',
      },
    },
  },
  plugins: [],
}
